version: "3.8"

networks:
  web-services:
    driver: bridge

services:
  web-app:
    build:
      context: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=database
      - DB_NAME=db_name
      - DB_USER=db_user
      - DB_PASSWORD=db_psw
    depends_on:
      - database

  database:
    image: postgres:14.6-alpine
    container_name: services_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db_name
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_psw