version: "3.8"

networks:
  web-services:
    driver: bridge


services:
  web-app:
    build:
      context: .
#    command: python manage.py runserver 8000
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: on-failure
    volumes:
      - ./service:/service


